# Generated by Django 3.0.5 on 2024-01-07 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('clients', models.ManyToManyField(blank=True, related_name='policies', to='app1.Client')),
                ('policy_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Client')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Policy')),
            ],
        ),
    ]
